### ISSUE TITLE
Support for the Hibernate specific annotation OptimisticLock

### ISSUE THREAD

**Issue by rainerschamm** [jakartaee/persistence#265] opened 2020-03-17 06:58 UTC
I would like to propose that this (Hibernate) annotation becomes part of the official JPA spec.

`
@OptimisticLock(excluded = true)
`

Docs:
[https://docs.jboss.org/hibernate/orm/5.4/javadocs/org/hibernate/annotations/OptimisticLock.html](url)

It would greatly improve the versatility of the existing optimistic locking functionality, since the developer would have much more fine grained control over which fields trigger an entity version increment.

**Comment by rbygrave** [comment] 2020-03-17 08:53
Isn't this a duplicate of https://github.com/eclipse-ee4j/jpa-api/issues/230 ?

**Comment by rainerschamm** [comment] 2020-03-17 13:13
Oh yea, sorry. I completely forgot about this. To be honest I only remember requesting this on the mailing list at the time.
Please merge or delete.

**Comment by gavinking** [comment] 2021-05-05 11:31
Either this issue of #230 should be closed.

**Closed** 2023-08-08 18:47 UTC
