### ISSUE TITLE
Consider adding convenience methods for wrapping transactions in Java SE environments

### ISSUE THREAD

**Issue by fwgreen** [jakartaee/persistence#204] opened 2019-01-24 00:40 UTC
Performing simple operations in Java SE environments has a lot of ceremony and the risk of getting it wrong.  I'm proposing adding some convenience methods to reduce both code bloat and guess work from the users end.  Here is my current approach:
```Java
public static void transaction(EntityManagerFactory emf, Consumer<EntityManager> operation) {
    var em = emf.createEntityManager();
    try {
	em.getTransaction().begin();
	operation.accept(em);
	em.getTransaction().commit();
    } catch (Throwable t1) {
	try {
	    em.getTransaction().rollback();
	} catch (Throwable t2) {
	    t2.printStackTrace();
	}
	throw t1;
    } finally {
	em.close();
    }
}
	
public static <E> E transaction(EntityManagerFactory emf, Function<EntityManager, E> operation) {
    var em = emf.createEntityManager();
    try {
	em.getTransaction().begin();
	E result = operation.apply(em);
	em.getTransaction().commit();
	return result;
    } catch (Throwable t1) {
	try {
	    em.getTransaction().rollback();
	} catch (Throwable t2) {
	    t2.printStackTrace();
	}
	throw t1;
    } finally {
	em.close();
    }
}
```
which allows me to use JPA like this:
```Java
public E update(E entity) {
    return transaction(emf, (EntityManager em) -> em.merge(entity));
}
	
public void save(E entity) {
    transaction(emf, (EntityManager em) -> em.persist(entity));
}
```

**Comment by gavinking** [comment] 2023-08-09 18:33
Apologies, @fwgreen, I opened #410 as a dupe of this one. That was my bad. 

(The issue title wasn't very clear, so I missed it.)

When #414 is done, we can close this.

**Closed** 2023-08-23 13:03 UTC
