### ISSUE TITLE
Modern search with json

### ISSUE THREAD

**Issue by gergelymolnarpro** [jakartaee/persistence#217] opened 2019-06-06 21:33 UTC
Standardise search with JSON (where, order by) as well as Criteria Queries/Builder.

**Comment by m-reza-rahman** [comment] 2021-04-27 21:16
This seems rather vague, a bit far-fetched and with no implementation precedent in any provider/project that I am aware. In the least a much more detailed proposal or prototype would be needed for this to have practical traction. I would suggest closing this to reduce clutter and focus on issues that have greater value-add for a wider set of users.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by beikov** [comment] 2021-04-28 06:47
I can only assume what the OP meant, but Blaze-Persistence adds functions for getting and setting values in JSON types on top of JPA for many databases: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/#json_get

**Comment by gavinking** [comment] 2021-04-28 10:34
@beikov if you have to guess at what functionality the issue is asking for, it's too vague. :-)

**Comment by gavinking** [comment] 2023-08-10 21:45
Closing this because the reporter has not clarified their request.

**Closed by gavinking** 2023-08-10 21:45 UTC
