### ISSUE TITLE
Add XML-less config to replace persistence.xml and orm.xml

### ISSUE THREAD

**Issue by hantsy** [jakartaee/persistence#358] opened 2022-02-05 03:58 UTC
Like the `@DataSourceDefinition`, add annotation config for JPA. 

And additionally provide the capability of using CDI beans(eg. like `EntityManagerFactorBean` role in Spring) to setup JPA.

**Comment by gavinking** [comment] 2023-08-10 14:35
@hantsy could you please give an example of what you're proposing here?

**Comment by gavinking** [comment] 2023-08-12 19:01
@hantsy I'm not very keen on the annotation. We _do_ have a thing like that which we use for testing Hibernate, so, I mean, there's precedent for it, but in terms of the spec it's unclear who would have the responsibility for discovering such annotations. If it's the EE container, then I don't see the annotation as very useful. Nor am I very keen on us just unilaterally imposing requirements on standalone CDI implementations. So I don't think that works.

On the other hand, a builder API similar to `Configuration` for bootstrapping an EMF would make plenty of sense. And as you show, this API should be rather easy to define, since its operations probably map pretty much 1-to-1 to elements of the `persistence.xml` (and, actually, to properties of `PersistenceUnitInfo`).

But, I dunno, I guess this would be more of a JPA 4.0 thing?

**Comment by gavinking** [comment] 2023-08-12 19:04
Note that this issue is essentially a dupe of #149 and #114.

**Comment by gavinking** [comment] 2023-08-13 16:13
> But, I dunno, I guess this would be more of a JPA 4.0 thing?

Screw it, it's easy enough to do, and there are three different issues requesting it.

Please review #465. (Still need to write some words for the spec, but the basic idea is in the Javadoc.)

**Closed** 2023-08-21 16:17 UTC
